// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD58-TbljWLy_UFcu1sr_6bOG871ttzees',
    appId: '1:1073474421111:web:69d6302795b658ea456172',
    messagingSenderId: '1073474421111',
    projectId: 'auth-and-crud-74',
    authDomain: 'auth-and-crud-74.firebaseapp.com',
    storageBucket: 'auth-and-crud-74.firebasestorage.app',
    measurementId: 'G-C0GNKE5X5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ApnU3WiTkA7-6MOnDh5ppn_MDWxygr8',
    appId: '1:1073474421111:android:b4fc509037093316456172',
    messagingSenderId: '1073474421111',
    projectId: 'auth-and-crud-74',
    storageBucket: 'auth-and-crud-74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrDFt_5li-gYClr-ii2lE-NyxamEISb1Q',
    appId: '1:1073474421111:ios:4e10ff7c51f4d1b0456172',
    messagingSenderId: '1073474421111',
    projectId: 'auth-and-crud-74',
    storageBucket: 'auth-and-crud-74.firebasestorage.app',
    iosBundleId: 'com.example.beanByte',
  );
}
